# Site settings
# --------------
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl: /
defaultContentLanguage: de
defaultContentLanguageInSubdir: true
enableGitInfo: true
title: "AutoScout24 GmbH"
destination: "../dist/"
relativeURLs: true
hrefTargetBlank: false

# Site Params
# -------------
params:
    description: ""
    author: "AutoScout24 GmbH"
    homeURL: https://www.autoscout24.de
    langtag: de-DE
    language: de
    country: DE
    environment: live
    basecatalog: /
    assetsBaseURL: https://www.autoscout24.de/assets/
    sitemapAssetsPath: assets/presse
