---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- type: text
  name: seotitle
  label: SEO Title
- type: datetime
  name: date
  label: Date
  config:
    required: true
- type: text
  name: city
  label: City
- type: textarea
  name: summary
  label: Summary (is visible on the list page)
- type: text
  name: subtitle
  label: Subtitle (for the press release page, highlighted section on the top of the
    text)
- type: select
  name: category
  config:
    source:
      type: simple
  label: Category
- type: file
  name: upload_pdf
  label: 'upload pdf:'
  description: here you can upload press release
  hidden: false
  config:
    maxSize: '500'
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
- type: select
  name: country
  config:
    source:
      type: simple
  label: Country
