baseURL: https://www.autoscout24.de/press/
theme: press-theme
defaultContentLanguage: de
defaultContentLanguageInSubdir: true
enableGitInfo: true
disableHugoGeneratorInject: true
canonifyURLs: true
staticDir: []
publishDir: public/press
outputs:
  section:
  - HTML
taxonomies:
  tag: "tags"
  category: "categories"
  date: "dates"
  year: "years"
  location: "locations"
params:
  homeURL: https://www.autoscout24.de
  langtag: de-DE
  language: de
  country: DE
  environment: live
  basecatalog: press
  assetsBaseURL: https://www.autoscout24.de/assets/press/
  sitemapAssetsPath: assets/press

Languages:
  de:
    baseURL: https://www.autoscout24.de/press/
    homeURL: https://www.autoscout24.de
    langtag: de-DE
    language: de
    country: DE
    assetsBaseURL: https://www.autoscout24.de/assets/press/

  at:
    baseURL: https://www.autoscout24.at/press/
    homeURL: https://www.autoscout24.at
    langtag: de-AT
    language: de
    country: AT
    assetsBaseURL: https://www.autoscout24.at/assets/press/

  nl:
    baseURL: https://www.autoscout24.nl/press/
    homeURL: https://www.autoscout24.nl
    langtag: nl-NL
    language: nl
    country: NL
    assetsBaseURL: https://www.autoscout24.nl/assets/press/

  fr:
    baseURL: https://www.autoscout24.fr/press/
    homeURL: https://www.autoscout24.fr
    langtag: fr-FR
    language: fr
    country: FR
    assetsBaseURL: https://www.autoscout24.fr/assets/press/

  it:
    baseURL: https://www.autoscout24.it/press/
    homeURL: https://www.autoscout24.it
    langtag: it-IT
    language: it
    country: IT
    assetsBaseURL: https://www.autoscout24.it/assets/press/

  nl-be:
    baseURL: https://www.autoscout24.be/nl/press/
    homeURL: https://www.autoscout24.be/nl/
    langtag: nl-BE
    language: nl
    country: BE
    publishDir: public/press/be
    assetsBaseURL: https://www.autoscout24.be/assets/press/

  fr-be:
    baseURL: https://www.autoscout24.be/fr/press/
    homeURL: https://www.autoscout24.be/fr/
    langtag: fr-BE
    language: fr
    country: BE
    publishDir: public/press/be
    assetsBaseURL: https://www.autoscout24.be/assets/press/

  es:
    baseURL: https://www.autoscout24.es/press/
    homeURL: https://www.autoscout24.es
    langtag: es-ES
    language: es
    country: ES
    assetsBaseURL: https://www.autoscout24.es/assets/press/

  com:
    baseURL: https://www.autoscout24.com/press/
    homeURL: https://www.autoscout24.com
    langtag: en-US
    language: en
    country: US
    disableKinds: ["taxonomy","taxonomyTerm","rss", "sitemap"]
    assetsBaseURL: https://www.autoscout24.com/assets/press/
