AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repo for press releases

Resources:

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: press-releases
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep no untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: AllowPush
          Effect: Allow
          Principal:
            AWS:
              - arn:aws:iam::544725753551:root
          Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:BatchGetImage
            - ecr:GetDownloadUrlForLayer
            - ecr:InitiateLayerUpload
            - ecr:PutImage
            - ecr:UploadLayerPart
            - ecr:CompleteLayerUpload
