---
upload_path: "/hugo/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/de/uploads/:year:/:month:/:day:"
body_file_url_template: "/de/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/forestry/admin"
webhook_url:
sections:
  pressreleases:
    default_front_matter_template: 1-press-release
version: 0.31.1
